services:
  dbot:
    restart: unless-stopped
    build:
      context: .
      target: final
    devices:
      - /dev/dri:/dev/dri
    ports:
      - '58008:58008'
    volumes:
     - ./.prod.env:/dbot/.env
     - ./prod-data:/dbot/prod-data
     - /tmp/dbot:/tmp/dbot
     - /attached-storage/server/static/bot/:/attached-storage/dbot
