services:
  dbot:
    restart: unless-stopped
    build:
      context: .
      target: final
    ports:
      - 58008:58008
    environment:
      DB_DIR: prod-data
    volumes:
     - ./prod-data:/dbot/prod-data

  minio:
    image: bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - './minio:/data'
    environment:
      - MINIO_ROOT_USER=root
      # needs to be at least 8 chars
      - MINIO_ROOT_PASSWORD=root1234
      - MINIO_DEFAULT_BUCKETS=dbot
