// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"dbot/pkg/db/types"
)

type Channel struct {
	Gid    string
	Chid   string
	ChName string
	Type   string
}

type Sound struct {
	Url     string
	Gid     string
	Aliases types.Aliases
}
